services:

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app-skeletal:latest
    container_name: kenchi
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      laravel-network:
        ipv4_address: 172.20.0.10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nextjs20:latest
    container_name: nextjs20
    restart: unless-stopped
    ports:
    - "80:3000"
    - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - laravel
    networks:
      laravel-network:
        ipv4_address: 172.20.0.30

  mysql:
    image: mysql:8.0
    container_name: kenchi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      laravel-network:
        ipv4_address: 172.20.0.20

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
